### PR TITLE
refactor: adapt for the new genertaed data(v2)

### PR DESCRIPTION
**Pull request by tyn1998**
Related:

 - #34

Change url to test the new data:

image

Or click this link: https://open-galaxy.x-lab.info/37/#/galaxy/open_galaxy?v=v2

### CODE REVIEW

**Comment by frank-zsy** [comment]
Great work and good to see `build-test` still works fine~

The problem for users are not linked to repos is caused by I only add link from user to repo but not repo to user. Although the graph should be undirected, galaxy still can not find the relationship backwards. I can export the data with both direction but the data is redundant. Should be able to modify the code to find the relationships from user to repo.

**Comment by tyn1998** [comment]
> Great work and good to see `build-test` still works fine~

Actually the two workflows were broken due to the changed build process but I fixed them. `/build-test` is so good!

> Although the graph should be undirected

Well, for me I think the graph should be single-directed and `user->repo` is fine for me. I think single direction makes sense and I will adapt the codebase to reveal all relationships that should be displayed. What do you think? @frank-zsy 

The original design:

image

Our adapation:

image

**Comment by frank-zsy** [comment]
But actually after you change the package manager from npm to yarn, I can not get the project work in my local env. Some GitHub url dependencies can not be installed and there are always some error after project start.

**Comment by tyn1998** [comment]
There are two prerequisites:

1. Node 14
2. git config --global url."https://github.com/".insteadOf git://github.com/

Are they satisfied?

reference: https://github.com/X-lab2017/open-galaxy#install

**Comment by tyn1998** [comment]
- [x] supports to display two kinds of nodes: repos and developers
- [x] the UI is also improved a bit.
- [x] change the default data to 'v2' 

image

Hi @frank-zsy, you can visit [the link](https://open-galaxy.x-lab.info/37/) to have a review :)

**Comment by tyn1998** [comment]
Do you think links should be toggled to be displayed by default? @frank-zsy

**Comment by frank-zsy** [comment]
LTGM, I think the links should be displayed by default now. And I think you should not manually change the default version to `v2`, I can change the `manifest.json` file to set the default version to `v2`.

**Comment by tyn1998** [comment]
> LTGM, I think the links should be displayed by default now.

OK, another commit will be pushed to change the default behavior.

> And I think you should not manually change the default version to `v2`, I can change the `manifest.json` file to set the default version to `v2`.

Yes, please. Could you name the default version as `2023-01` or `202301`? In that way, users can get time info from urls so they don't need to ask: "Why my project is not in the graph?" The reason is his/her project was not active in `2023-01`

**Comment by frank-zsy** [comment]
> Yes, please. Could you name the default version as `2023-01` or `202301`? In that way, users can get time info from urls so they don't need to ask: "Why my project is not in the graph?" The reason is his/her project was not active in `2023-01`

Of course, that could be done as well.

**Comment by frank-zsy** [comment]
The data has been updated, is this PR ready to review?

**Comment by tyn1998** [comment]
Great! it is ready for review.

/build-test

**Comment by frank-zsy** [comment]
Unlike Hypertrons command which can parse command for any line in a comment, the build test action need the comment body exactly match the command to work @tyn1998

**Comment by frank-zsy** [comment]
LGTM, great work.

/approve

**Pull request merged**
