### PR TITLE
add RFC.md

### PR DESCRIPTION
**Pull request by gymgym1212**
Now, the RFC.md is an empty template.

Signed-off-by: Yeming Gu <yeminggood@gmail.com>

### CODE REVIEW

**Comment by frank-zsy** [comment]
Can you finish this PR before Friday? @gymgym1212

**Comment by gymgym1212** [comment]
Now I have modified the first three parts, and the rest are design and testing. Would you consider writing this for me? At present, I may not be familiar with the overall architecture. If there is nothing to write about `Testing` part, we can consider deleting it. @frank-zsy @tyn1998

**Comment by gymgym1212** [comment]
And some words may not be very appropriate. What do you think needs to be changed?

**Comment by tyn1998** [comment]
No testing yet, I suppose.

**Comment by frank-zsy** [comment]
I can merge this PR first and add some details about design and testing part.

**Pull request merged**
