### PR TITLE
Update packages & A new webpack setup & Remove useless files & Update info in package.json

### PR DESCRIPTION
**Pull request by tyn1998**
- React: v0.14.5  -->  v17.0.2
- Webpack: v1.9.11  -->  v5.64.4
- ...

So this PR must be a huge update.

### CODE REVIEW

**Comment by frank-zsy** [comment]
image

The build test website can not load on my browser and there are two js files (365.js, main.js) are in the root path rather than PR path.

Is webpack configured right?

**Comment by tyn1998** [comment]
It was due to a wrong output.publicPath in webpack.config.js, I just fixed it.

Here is why:
- publicPath: "/" --> relative to server  
- publicPath: "" --> relative to HTML file

**Comment by frank-zsy** [comment]
It works fine on my side, all elements are rendered as before.

**Pull request merged**
